// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9gYuljzbEU9UYcI8Py1Yi0VJAiUXkwo',
    appId: '1:61494954148:web:54477252338ac85f1abe31',
    messagingSenderId: '61494954148',
    projectId: 'hrm-1-21821',
    authDomain: 'hrm-1-21821.firebaseapp.com',
    storageBucket: 'hrm-1-21821.firebasestorage.app',
    measurementId: 'G-V18LS5BR55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggLGhbet1WDKYPjimfDZvnUYTXcWIsDQ',
    appId: '1:61494954148:android:c2c84cbf20536db81abe31',
    messagingSenderId: '61494954148',
    projectId: 'hrm-1-21821',
    storageBucket: 'hrm-1-21821.firebasestorage.app',
  );
}
